#!/bin/bash

PKG_CMAKE_OPTS_TARGET+=" -DUSE_HOST_LIBZIP=OFF -DUSE_HOST_SDL=OFF"
PKG_CMAKE_OPTS_TARGET+=" -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE"

if [[ "${ARCH}" = "aarch64" && "${DEVICE}" = "RPi5" ]]; then
  PROJECT_CFLAGS="-DPAGE_SIZE=16384"
fi

sed -i '400 a\	target_link_libraries(${PROJECT_NAME} PRIVATE atomic)' ${SOURCE_DIR}/CMakeLists.txt

# Remove when https://github.com/flyinghead/flycast/issues/1688 is resolved
sed -i 's/\\U//g' ${SOURCE_DIR}/shell/libretro/libretro_core_options_intl.h
